apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: us-central1-docker.pkg.dev/peak-axiom-426310-b1/gke-repo/dockerimage2
          ports:
            - containerPort: 3332

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 3332
      targetPort: 3332
  type: LoadBalancer
